# Invoke the /api/cleanup endpoint once a day to delete boards that have expired.
# If you're running your own instance, change the URL in the last line accordingly.
name: cleanup-cronjob
on:
  schedule:
    - cron: '5 0 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up expired rows
        run: |
          curl --request POST \
          --url 'https://tempchan.com/api/cleanup'
